# NUMPY LIBRARY

# CREATING AN ARRAY

In [3]:
import numpy as np
x= np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


#array


In [3]:
import numpy as np
x=[1,2,3,4,5]
y=np.array(x)
print(y)
print(type(y))
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
<class 'list'>


In [7]:
l=[]
for i in range(1,5):
   a= int(input("enter :"))
   l.append(a)
print(l)

enter : 10
enter : 20
enter : 30
enter : 40


[10, 20, 30, 40]


In [9]:
import numpy as np
a=[1,2,3,4,5,6,7]
b=np.array(a)
print(b)
print(type(b))
print(b.ndim)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
1


In [14]:
import numpy as np
a= np.array([[1,2,3,4],[1,2,3,4]])
print(a)
print(a.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [15]:
a = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(a)
print(a.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [17]:
a= np.array([1,2,3,4],ndmin=10)
print(a)
print(a.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# CREATING NUMPY ARRAY USING NUMPY FUNCTIONS

**array filled with 0's**

In [4]:
import numpy as np
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [6]:
ar_zero1 = np.zeros((3,4))
print(ar_zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**array filled with 1's**

In [7]:
import numpy as np
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [26]:
ar_one1 = np.ones((4,4))
print(ar_one1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**create an empty array**

In [11]:
import numpy as np
ar_empt = np.empty((2,2))
print(ar_empt)

[[1. 1.]
 [1. 1.]]


**an array with a range of elements**

In [13]:
import numpy as np
ar_rn = np.arange(10)
print(ar_rn)

[0 1 2 3 4 5 6 7 8 9]


**array diogonal elememnts filled with 1's**

In [16]:
import numpy as np
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**create an array with value that one spaced llinealry in a specific interval**

In [20]:
import numpy as np
ar_lin = np.linspace(1,5,num=5)
print(ar_lin)

[1. 2. 3. 4. 5.]


# CREATE NUMPY ARRAYS WITH RANDOM NUMBERS

#we have 4 functions for random numbers
1. rand()
2. randn()
3. ranf()
4. randint()

In [30]:
import numpy as np
var = np.random.rand(4,3)
print(var)

[[0.50848776 0.04423864 0.14650875]
 [0.90985829 0.01465727 0.41301015]
 [0.58245152 0.11988007 0.44208693]
 [0.74058904 0.25135514 0.87580188]]


In [31]:
import numpy as np
var1 = np.random.randn(4)
print(var1)

[-1.42779758  0.13127335  0.20608122  0.71996827]


In [32]:
import numpy as np
var2 = np.random.ranf(5)
print(var2)

[0.09316522 0.35953225 0.7613835  0.28304292 0.2044143 ]


In [33]:
import numpy as np
var3 = np.random.randint(1,10,5)
print(var3)

[9 3 8 2 7]


# data type 

In [5]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9,10])
print(var)
print()
print("data type:", var.dtype)

[ 1  2  3  4  5  6  7  8  9 10]

data type: int64


In [7]:
import numpy as  np
var1 = np.array(["omi","khushi","kartik"])
print(var1)
print("data type:", var1.dtype)

['omi' 'khushi' 'kartik']
data type: <U6


In [9]:
import numpy as np
var2= np.array(["a","b","c",1,2,3,4])
print(var2)
print("data type:",var2.dtype)

['a' 'b' 'c' '1' '2' '3' '4']
data type: <U21


# type conversion

In [13]:
x = np.array([1,2,3,4,5],dtype=np.int8)
print(x)
print("Data array:",x.dtype)

[1 2 3 4 5]
Data array: int8


In [14]:
x = np.array([1,2,3,4],dtype = "f")
print(x)
print("data type:",x.dtype)

[1. 2. 3. 4.]
data type: float32


**using function**

In [15]:
x = np.array([1,2,3,4,5])
new = np.float32(x)
print(x)
print(x.dtype)
print()
print(new)
print(new.dtype)

[1 2 3 4 5]
int64

[1. 2. 3. 4. 5.]
float32


In [2]:
import numpy as np
x = np.array([1,2,3,4,5])
new = x.astype(float)
print(x)
print(new)
print(x.dtype)
print(new.dtype)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
int64
float64


# shape and reshaping in numpy array

**shape**

In [4]:
import numpy as np
var = np.array([[1,2],[3,4]])
print(var)
print(var.ndim)
print(var.shape)

[[1 2]
 [3 4]]
2
(2, 2)


In [5]:
var1 = np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.ndim)
print(var1.shape)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


**reshape**

In [7]:
import numpy as np
var = np.array([1,2,3,4,5,6])
x = var.reshape(3,2)
print(var)
print()
print(x)

[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]


In [11]:
#for 3 dimention
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x = var.reshape(2,3,2)
print(var)
print()
print(x)
               

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x = var.reshape(2,3,2)
print(var)
print()
print(x)
new = x.reshape(-1)
print(new)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Arithmetic operations

**In 1d array**

In [7]:
import numpy as np
var = np.array([1,2,3,4,5])
varadd = var+3
print("array :",var)
print()
print("after addition of 3")
print(varadd)

array : [1 2 3 4 5]

after addition of 3
[4 5 6 7 8]


In [9]:
import numpy as np  
var1 = np.array([1,2,3,4])
varsub = var1-3
print(varsub)

[-2 -1  0  1]


In [10]:
import numpy as np 
var2 = np.array([1,2,3,4])
varmul = var2*3
print(varmul)

[ 3  6  9 12]


In [11]:
import numpy as np
var3  = np.array([1,2,3,4])
vardiv = var3/3
print(vardiv)

[0.33333333 0.66666667 1.         1.33333333]


In [12]:
import numpy as np 
var4 = np.array([1,2,3,4])
vardmod = var4%3
print(vardmod)

[1 2 0 1]


In [15]:
import numpy as np
var5 = np.array([1,2,3,4])
varpow= var5**2
print(varpow)

[ 1  4  9 16]


#operation between 2 arrays

In [18]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
add = a+b
print("first array:",a)
print("second array:",b)
print()
print("addition of both:",add)

first array: [1 2 3 4]
second array: [1 2 3 4]

addition of both: [2 4 6 8]


In [19]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = np.add(a,b)
print(c)

[2 4 6 8]


In [20]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = a-b
print(c)

[0 0 0 0]


In [21]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = np.subtract(a,b)
print(c)

[0 0 0 0]


In [22]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = a*b
print(c)

[ 1  4  9 16]


In [24]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = np.multiply(a,b)
print(c)

[ 1  4  9 16]


In [25]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = a%b
print(c)

[0 0 0 0]


In [27]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = np.mod(a,b)
print(c)

[0 0 0 0]


In [28]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = a**b
print(c)

[  1   4  27 256]


In [29]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = np.power(a,b)
print(c)

[  1   4  27 256]


In [30]:
import numpy as np 
a = np.array([1,2,3,4])
b = np.reciprocal(a)
print(b)

[1 0 0 0]


**in 2d array**

In [34]:
import numpy as np 
var1 = np.array([[1,2,3],[1,2,3]])
var2 = np.array([[1,2,3],[1,2,3]])
var3 = var1 + var2 
print(var1)
print()
print(var2)
print()
print(var3)


[[1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]]

[[2 4 6]
 [2 4 6]]


# Arithmetic functions

**for 1d arrays**

In [40]:
import numpy as np
var = np.array([7,9,67,23,45,90])
print("minimum value:",np.min(var))
print("maximum value:",np.max(var))
print(np.argmin(var))
print(np.sqrt(var))
print(np.sin(var))
print(np.cos(var))
print(np.cumsum(var))

minimum value: 7
maximum value: 90
0
[2.64575131 3.         8.18535277 4.79583152 6.70820393 9.48683298]
[ 0.6569866   0.41211849 -0.85551998 -0.8462204   0.85090352  0.89399666]
[ 0.75390225 -0.91113026 -0.5177698  -0.53283302  0.52532199 -0.44807362]
[  7  16  83 106 151 241]


**for 2d**

In [41]:
import numpy as np
var = np.array([[2,1,3],[9,5,6]])
print(np.min(var, axis=0))

[2 1 3]


# Broadcasting

In [4]:
import numpy as np 
var = np.array([1,2,3,4])
var1 = np.array([1,2,3,4])
print(var)
print(var.shape)
print(var1)
print(var1.shape)
print(var+var1)

[1 2 3 4]
(4,)
[1 2 3 4]
(4,)
[2 4 6 8]


In [12]:
import numpy as np
var= np.array([1,2,3])
var1= np.array([[1],[2],[3]])
print(var)
print(var.shape)
print()
print(var1)
print(var.shape)
print()
print(var + var1)

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3,)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [15]:
import numpy as np 
var = np.array([[2],[1]])
var1 = np.array([[1,2,3],[1,2,3]])
print(var)
print(var.shape)
print()
print(var1)
print(var1.shape)
print()
print(var+var1)

[[2]
 [1]]
(2, 1)

[[1 2 3]
 [1 2 3]]
(2, 3)

[[3 4 5]
 [2 3 4]]


# Indexing and slicing in numpy arrays

**indexing**

#in 1d array

In [3]:
import numpy as np
var = np.array([7,8,4,5,3,2,9,0,6])
print(var[1])
print(var[-6])

8
5


#in 2d array

In [8]:
import numpy as np
var = np.array([[1,2,3],[4,5,6]])
print(var)
print(var[1,1])

[[1 2 3]
 [4 5 6]]
5


#in 3d array

In [12]:
import numpy as np 
var = np.array([[[1,2,3],[2,3,4]],[[5,4,6],[1,23,34]]])
print(var)
print(var.ndim)
print(var[1,1,1])

[[[ 1  2  3]
  [ 2  3  4]]

 [[ 5  4  6]
  [ 1 23 34]]]
3
23


**Slicing**

In [8]:
import numpy as np
var = np.array([1,2,3,4,5,6,7])
print(var)
print("2 to 5:",var[1:5])
print("2 to end:",var[1:])
print("start to 5:",var[:5])
print("stop:",var[::2])


[1 2 3 4 5 6 7]
2 to 5: [2 3 4 5]
2 to end: [2 3 4 5 6 7]
start to 5: [1 2 3 4 5]
stop: [1 3 5 7]


In [9]:
#in 2d

In [11]:
import numpy as np
var = np.array([[1,2,3,4],[5,6,7,8],[9,2,3,5]])
print(var)
print()
print("6 to 8:",var[1,1:])


[[1 2 3 4]
 [5 6 7 8]
 [9 2 3 5]]

6 to 8: [6 7 8]


# iterating numpy array

In [1]:
import numpy as np
var = np.array([9,8,7,6,5,4,3,2,1])
print(var)
for i in var:
    print(i)

[9 8 7 6 5 4 3 2 1]
9
8
7
6
5
4
3
2
1


In [5]:
import numpy as np 
var = np.array([[1,2,3],[4,5,6]])
print(var)
print(var.ndim)
print()

for i in var:
    for j in i:
        print(j)


[[1 2 3]
 [4 5 6]]
2

1
2
3
4
5
6


In [8]:
import numpy as np
var = np.array([[[1,2,3],[4,5,6]]])
print(var)
for i in var:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6


#nditer() function

In [25]:
import numpy as np 
var = np.array([[[1,2,3],[4,5,6]]])
for i in np.nditer(var):
    print(i)

1
2
3
4
5
6


In [17]:
import numpy as np 
var = np.array([[[1,2,3],[4,5,6],[1,2,4]]])
for i in np.nditer(var,flags=['buffered'],op_dtypes=['int']):
    print(i)

1
2
3
4
5
6
1
2
4


In [18]:
#ndenumerate()

In [19]:
import numpy as np 
var = np.array([[[1,2,3],[4,5,6],[1,2,4]]])
for i in np.ndenumerate(var):
    print(i)

((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 0, 2), np.int64(3))
((0, 1, 0), np.int64(4))
((0, 1, 1), np.int64(5))
((0, 1, 2), np.int64(6))
((0, 2, 0), np.int64(1))
((0, 2, 1), np.int64(2))
((0, 2, 2), np.int64(4))


# copy vs view

In [23]:
import numpy as np
var = np.array([1,2,3,4])
copy = var.copy()
var[1]=40
print(var)
print("copy:",copy)

[ 1 40  3  4]
copy: [1 2 3 4]


In [24]:
import numpy as np
var = np.array([1,2,3,4])
view = var.view()
var[1]=40
print(var)
print("view:",view)

[ 1 40  3  4]
view: [ 1 40  3  4]


# Join and split function

**join**

In [1]:
import numpy as np
var = np.array([1,2,3,4,5,6,7])

var1 = np.array([1,2,3,4,5,6,7])

ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 5 6 7 1 2 3 4 5 6 7]


#for 2d

In [4]:
import numpy as np
var = np.array([[1,2,],[3,4]])
var1 = np.array([[9,6],[7,6]])
ar = np.concatenate((var,var1),axis=0)
print(ar)

[[1 2]
 [3 4]
 [9 6]
 [7 6]]


In [1]:
import numpy as np
var = np.array([[1,2,],[3,4]])
var1 = np.array([[9,6],[7,6]])
ar = np.concatenate((var,var1),axis=1)
print(ar) 

[[1 2 9 6]
 [3 4 7 6]]


In [2]:
import numpy as np 
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])
ar_new = np.stack((var,var1),axis=1)
print(ar_new)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [3]:
import numpy as np 
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])
ar_new = np.stack((var,var1),axis=0)
print(ar_new)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
#hstack 
#vstack
#dstack

import numpy as np
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])
ar_new = np.hstack(var, var1)
print(ar_new)

In [2]:
import numpy as np
var = np.array([1,2,3,4]) 
var1 = np.array([5,6,7,8])
ar_new = np.hstack((var, var1))
print(ar_new)

[1 2 3 4 5 6 7 8]


In [3]:
import numpy as np
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])
ar_new = np.vstack((var, var1))
print(ar_new)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
import numpy as np
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])
ar_new = np.dstack((var, var1))
print(ar_new)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


**split**

In [7]:
import numpy as np
var = np.array([1,2,3,4,5,6])
print(var)
ar = np.array_split(var,3)
print(ar)
print(ar[0])
print(var[0])

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
1


In [8]:
#for 2d 


In [11]:
var = np.array([[1,2],[3,4],[5,6]])
print(var)
ar_1 = np.array_split(var,3)
print()
print(ar_1)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [12]:
var = np.array([[1,2],[3,4],[5,6]])
print(var)
ar_1 = np.array_split(var,3,axis=1)
print()
print(ar_1)

[[1 2]
 [3 4]
 [5 6]]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]


# search,sort,search shorted,filter functions

**search array**

In [20]:
import numpy as np
var = np.array([11,56,57,86,88,67,23,44,90])
x = np.where(var==86)
print(x)

(array([3]),)


In [21]:
import numpy as np
var = np.array([32,34,33,56,78,98,23,90])
y = np.where((var%2)==0)
print(y)

(array([0, 1, 3, 4, 5, 7]),)


**sort array**

In [2]:
import numpy as np
var = np.array([1,27,3,94,54,6])
print(np.sort(var))

[ 1  3  6 27 54 94]


In [3]:
import numpy as np
var = np.array(["a","s","d","f"])
print(np.sort(var))

['a' 'd' 'f' 's']


In [4]:
import numpy as np
var = np.array([[4,3,2],[1,12,5],[22,52,6]])
print(np.sort(var))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


**search sorted array**

In [6]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8])
x   = np.searchsorted(var,5)
print(x)

4


In [8]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,8])
x = np.searchsorted (var,5,side="right")
print(x)

5


**filter array**

In [11]:
import numpy as np 
var = np.array(["a","s","d","f])
f = [True,False,False,True]
new = var[f]

print(new)
print(type(new))

['a' 'f']
<class 'numpy.ndarray'>


# shuffle, unique, resize, flatten,ravel functions

**shuffle**

In [12]:
import numpy as np
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[3 4 5 1 2]


**unique**

In [19]:
import numpy as np 
var = np.array([1,2,3,4,5,5,6,7,8])
x = np.unique(var)
print(x)
y = np.unique(var,return_index=True)
print(y)
z = np.unique(var,return_counts=True)
print(z)

[1 2 3 4 5 6 7 8]
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([0, 1, 2, 3, 4, 6, 7, 8]))
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([1, 1, 1, 1, 2, 1, 1, 1]))


**resize**

In [5]:
import numpy as np 
var = np.array([1,2,3,4,5,6])
y = np.resize(var,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


**flatten**

In [14]:
import numpy as np 
var = np.array([1,2,3,4,5,6,7])
y = np.resize(var,(3,2))
print(var)
print()
print(y)
print()
print(y.flatten())
print()
print(y.flatten(order="F"))

[1 2 3 4 5 6 7]

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]

[1 3 5 2 4 6]


**reval**

In [2]:
import numpy as np
var= np.array([[1,2,3],[4,5,6]])
print( np.ravel(var))

[1 2 3 4 5 6]


In [5]:
import numpy as np 
var= np.array([[1,2,3],[4,5,6]])
print(np.ravel(var,order="F"))

[1 4 2 5 3 6]


# insert and delete function

In [5]:
import numpy as np
var = np.array([1,2,3,4])
print(var)
print(type(var))
x = np.insert(var,2,40)
print(x)
y = np.insert(var,(2,3),40)
print(y)

[1 2 3 4]
<class 'numpy.ndarray'>
[ 1  2 40  3  4]
[ 1  2 40  3 40  4]


In [6]:
import numpy as np
var1 = np.array([[1,2,3],[1,2,3]])
var2 = np.insert(var1, 1 , 6, axis=1)
print(var2)

[[1 6 2 3]
 [1 6 2 3]]


In [9]:
x = np.append(var1, 6.5)
print(x)

[1.  2.  3.  1.  2.  3.  6.5]


In [14]:
x = np.append(var1,[[45,44,53]])
print(x)

[ 1  2  3  1  2  3 45 44 53]


In [2]:
import numpy as np
var1 = np.array([1,2,3,4])
print(var1)
d = np.delete(var1,2)
print(d)

[1 2 3 4]
[1 2 4]


# Matrix in numpy array

In [5]:
import numpy as np
var = np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [6]:
import numpy as np
var = np.array([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


**arithmetic operation**

In [17]:
import numpy as np
var = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
var1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(var)
print()
print(var1)
print()
print("edition")
print(var+var1)
print()
print("substraction")
print(var-var1)
print()
print("multiplication")
print(var.dot(var1))
print()
print(var*var1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

edition
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

substraction
[[0 0 0]
 [0 0 0]
 [0 0 0]]

multiplication
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


**Matrix function**

In [20]:
import numpy as np
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))
print()
print("or")
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

or
[[1 4]
 [2 5]
 [3 6]]


In [30]:
import numpy as np
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [32]:
import numpy as np
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.inv(var))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
import numpy as np
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.matrix_power(var,2))
print()
print(np.linalg.matrix_power(var,0))
print()
print(np.linalg.matrix_power(var,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [13]:
import numpy as np
var = np.matrix([[1,2],[4,5]])
np.linalg.det(var)

np.float64(-2.9999999999999996)